//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHang001.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        public int ID { get; set; }

        [DisplayName("Tên người dùng")]
        [Required(ErrorMessage = "Vui lòng nhập tên!")]
        [StringLength(50, ErrorMessage = "Số lượng ký tự không quá 50!")]
        public string NameUser { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập Role!")]
        public string RoleUser { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Password!")]
        public string PasswordUser { get; set; }

        [NotMapped]
        [Compare("PasswordUser", ErrorMessage = "Password chưa đúng! Vui lòng nhập lại.")]
        public string ConfirmPass { get; set; }
    }
}
