//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHang001.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Category
    {
        public Category()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        [DisplayName("Mã danh mục")]    
        public string IDCate { get; set; }
        [DisplayName("Tên danh mục")]
        public string NameCate { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
