//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHang001.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            ImagePro = "`/images/1.png";
        }


        [DisplayName("Mã sản phẩm")]
        public int ProductID { get; set; }

        [DisplayName("Tên sản phẩm")]
        public string NamePro { get; set; }

        [DisplayName("Mô tả")]
        public string DecriptionPro { get; set; }


        [DisplayName("Danh mục")]
        public string IDCate { get; set; }


        [Range(1000, 500000000, ErrorMessage = "1000=<Price=<50000")]
        [DisplayName("Giá")]
        public Nullable<decimal> Price { get; set; }

        [DisplayName("Hình ảnh")]
        public string ImagePro { get; set; }


        [NotMapped]
        public HttpPostedFileBase ImagePath { get; set; }


        public virtual Category Category { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
